### ISSUE TITLE
support serverless remove

### ISSUE THREAD

**Issue by johndww** [rrahul963/serverless-create-global-dynamodb-table#4]
serverless remove should delete all the backup tables and global table connection. I'm working on the patch now using the
```
      'remove:remove': function () {
        deleteGlobalAndBackupTables(serverless)
      },
```

hook. PS love the plugin, there is really limited support for deploying global tables without cloudformation.

**Comment by johndww** [comment]
@rrahul963  I don't see any open issues on either PRs. Can you link me?

**Comment by rrahul963** [comment]
tagged you @johndww

**Comment by johndww** [comment]
is this what you mean? That I should add a comment linking this issue?

**Comment by johndww** [comment]
@rrahul963 can you merge the two PRs if there are no more issues? Thanks

**Comment by johndww** [comment]
@rrahul963 can you merge this please?

**Comment by rrahul963** [comment]
@johndww - with the latest version of package we'll need to redo this
