### ISSUE TITLE
Failing silently

### ISSUE THREAD

**Issue by lukekhamilton** [rrahul963/serverless-create-global-dynamodb-table#7]
Hey I have just set this plugin up and it looks to be failing silently.

When I fun a sls deploy -v I am getting the following put: 

```
CreateGlobalTable: Starting setting up global tables...
```
And then dropping back into the terminal with no more messages and then in the AWS console it looks like nothing has happened at all. 

Please advise best way to debug. 
Thanks

**Comment by rrahul963** [comment]
@lukekhamilton - this has been fixed in latest version.
